### ISSUE TITLE
PMV - DBT limits

### ISSUE THREAD

**Issue by vwdevargas** [CenterForTheBuiltEnvironment/pythermalcomfort#1]
Hello, @FedericoTartarini. Congratulations for your work and thank you for sharing it! You've saved me a lot of time!

I've tried to use your implementation for different scenarios, running loops and varying DTB, RU, WV (wind velocity) and it worked really well. However, there is a limitation for the effect of WV in the PMV model: depending on temperature, it stops cooling. For simulations increasing in 1ºC, it stops when DTB is above 33ºC (I'm using `MRT=DTB`).

Here's the PMV calling inside the loops:
```
WV_r = v_relative(WV,MET)
PMV = pythermalcomfort.pmv(DBT,MRT,WV_r,RU,MET,CLO,standard='ISO')
line = {'MET':MET,'CLO':CLO,'MRT [C]':MRT,'DBT [C]':DBT,'RU [%]':RU,'WV [m/s]':WV,'PMV n':PMV,'PMV':PMV_name}
CT_test = CT_test.append(line, ignore_index=True)
```

Here are the outputs I'm addressing (there as XLSX file attached):
```
MET | CLO | MRT [C] | DBT [C] | RU [%] | WV [m/s] | PMV n | PMV
-- | -- | -- | -- | -- | -- | -- | --
1,4 | 0,57 | 34 | 34 | 45 | 0,1 | 2,73 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 0,3 | 2,74 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 0,6 | 2,75 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 1 | 2,76 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 1,3 | 2,77 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 1,6 | 2,77 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 2 | 2,78 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 2,3 | 2,78 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 2,6 | 2,78 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 3 | 2,79 | Hot
1,4 | 0,57 | 34 | 34 | 45 | 4 | 2,8 | Hot
```
[github_pythermalcomfort_pmvScenarios.xlsx](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/files/4452268/github_pythermalcomfort_pmvScenarios.xlsx)

As you can see, as I increase the WV, for the same conditions in other variables, the PMV doesn't decrease. Am I missing something?

![image](https://user-images.githubusercontent.com/43864446/78821821-77d6eb00-79b0-11ea-9930-7d9ce436b929.png)

Also, do you know if there's a function which limits WV for the ISO standard? From what I've analyzed, you only generate warnings -- which are being raised in intervals different from the warnings, as shown below. I'd also like to use WV up to 10m/s in my simulations and, for what I've tested, there isn't anything that would interfere, but I'd love if you could confirm that to me.

```
    elif params['standard'] == 'iso':  # based on table 7.3.4 ashrae 55 2017
        for key, value in params.items():
            if key == 'tdb':
                if value > 30 or value < 10:
                    warnings.warn("ISO air temperature applicability limits between 10 and 50 °C", UserWarning)
            if key == 'tr':
                if value > 40 or value < 10:
                    warnings.warn("ISO air temperature applicability limits between 10 and 50 °C", UserWarning)
            if key in ['v', 'vr']:
                if value > 1 or value < 0:
                    warnings.warn("ISO air velocity applicability limits between 0 and 2 m/s", UserWarning)
            if key == 'met':
                if value > 4 or value < 0.8:
                    warnings.warn("ISO met applicability limits between 1.0 and 2.0 met", UserWarning)
            if key == 'clo':
                if value > 2 or value < 0:
                    warnings.warn("ISO clo applicability limits between 0.0 and 1.5 clo", UserWarning)
```

Again, thank you and congratulations for your work!

Obs.: I'm currently running Python 3.7 through Anaconda, in Windows 10.

**Comment by FedericoTartarini** [comment]
Hi @vwdevargas I am happy you found the package useful.

It is completing normal that the heat loss component from the clothing surface stops when the Tdb reaches a certain value, in fact if you keep increasing Tdb then the convective component would increase the heat gains to the body. This is due to the fact that the PMV estimates a certain skin temperature value, if the air temperature is below this value then we have convective heat losses from the body to the ambient, however, if the air temperature is higher than the skin temperature then the body would gain heat. Please visit [this webpage](https://comfort.cbe.berkeley.edu), use the drop down bar over the chart to select the "thermal heat losses..." chart and at the bottom of the chart click on " convection from clothing surface". The line you have activated shows that below a certain air temperature the body loses heat to the environment while above that value the body gains heat from the environment. I hope I have answered your first question.

I have noticed that there may be few small errors in the comments of my function which raises the warning, I will try to fix that as soon as possible. However, keep in mind that the ISO 7730 states that PMV calculation is only valid between 0 and 1 m/s. You are of course free to use any value of air velocity as you want but please keep in mind that the value you get may be wrong since outside the applicability limit of the PMV function. The fact that the function return a value does not mean that the value is correct. Please keep that in mind. 

I hope I have answered all your questions.

**Comment by vwdevargas** [comment]
Dear @FedericoTartarini,

Your explanations make total sense. However when I test it on your webpage, even if the Tdb is bigger than 40ºC, PMV decreases as WV increases. I don't know if this is due to the fact that I'm using MRT=Tdb, since your website doesn't demand this input. Do you use any approximation of MRT I could use with the same inputs in order to get the same results from the webpage?

Thank you for your comment on the limits. I'll consider that in my application.

I apologize if I'm missing something, since my field is electrical engineering. I've only covered basics of thermodynamics and psychrometrics.

**Comment by FedericoTartarini** [comment]
From your first message I am assuming you have selected "ISO" for the PMV calculation in the pythermalcomfort package. If that is the case try to compare the results you get from the PMV function which those you get from [this page](https://comfort.cbe.berkeley.edu/EN). Technically the two values should be the same. The website is calculating PMV using a function written in JavaScript. But the two should return the same value.

Technically if you select Tair = Tmrt =40 degC and you keep increasing the air velocity the PMV should increase as well, which means that the person is gaining more heat from the environment (e.g. feeling hotter). Or at least that is what happens if you do so in the CBE thermal comfort tool website.

**Comment by FedericoTartarini** [comment]
I just tried to do that and @vwdevargas you are right, there is an issue somewhere since if you set Tair = Tmrt =40 degC and you keep increasing the value of air speed in the CBE thermal comfort tool page the PMV keeps increasing while in the pythermalcomfort package as the air velocity increases the PMV decreases which is not right. See an example [here](https://colab.research.google.com/drive/18cVyQlPYl-Wv-mHxSyUQpHMH2LBHSeMU). Thank you so much for finding this issue. I will look into it tomorrow. I am in Singapore and now is almost midnight :)

**Comment by FedericoTartarini** [comment]
> I just tried to do that and @vwdevargas you are right, there is an issue somewhere since if you set Tair = Tmrt =40 degC and you keep increasing the value of air speed in the CBE thermal comfort tool page the PMV keeps increasing while in the pythermalcomfort package as the air velocity increases the PMV decreases which is not right. See an example [here](https://colab.research.google.com/drive/18cVyQlPYl-Wv-mHxSyUQpHMH2LBHSeMU). Thank you so much for finding this issue. I will look into it tomorrow. I am in Singapore and now is almost midnight :)

@vwdevargas sorry for the previous message but in fact everything is fine. If you select "ISO" in the function you see the expected behavior: as the air velocity increases the PMV increases as well. On the other and if you select ASHRAE, as the air velocity increases the PMV decreases since in the ASHRAE they firstly calculate the cooling effect [here](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c1d86272b6a30d63929eeff011a9536be7eb90c2/src/pythermalcomfort/models.py#L165). However, this I think is an issue, which I will try to raise with the ASHRAE committee.

**Comment by vwdevargas** [comment]
Perfect. I now get the same behaviour using the ASHRAE standard. I'd be interested to know if this is an issue or not, though I'm guessing it is, considering your explanation on convective heat gains in higher temperatures.

We're working on very different time zones, since I'm from Brazil, hehe. Thank you so much for your fast and detailed answers! Best regards.
