### ISSUE TITLE
numpy api for utci

### ISSUE THREAD

**Issue by larsbuntemeyer** [CenterForTheBuiltEnvironment/pythermalcomfort#23]
Hey everybody,
we would be interested in using some thermal comfort indicators on gridded datasets, e.g., `numpy` arrays. I am not sure how you think about this. In general it only requires minor changes, e.g., replacing `if` statements with `np.where` and returning `np.nan` instead of raising errors or warning. I have implemented the `utci` index as an example (i can show in a pull request) and the changes in the code are really minor. I think other indicators could be adapted too and they would still work on single floats but also on whole numpy arrays....

**Comment by larsbuntemeyer** [comment]
related to #11

**Comment by FedericoTartarini** [comment]
Hi thank you for your suggestion, I like the idea of allowing users to use arrays as input. Thank you for starting implementing the code in the UTCI. I will review your changes. 

Federico

**Comment by larsbuntemeyer** [comment]
thanks for looking at this!

**Comment by larsbuntemeyer** [comment]
just by the way, can you explain a little what [utci_optimized](https://github.com/larsbuntemeyer/pythermalcomfort/blob/d2ccac9593e58b288b9a027070f9c765a6c5b574/src/pythermalcomfort/optimized_functions.py#L408) is doing?

The implementation looks a little complicated, is that a `numba` compilation thing? I don't really have much experience with that....

**Comment by FedericoTartarini** [comment]
I wrapped the [utci_optimized](https://github.com/larsbuntemeyer/pythermalcomfort/blob/d2ccac9593e58b288b9a027070f9c765a6c5b574/src/pythermalcomfort/optimized_functions.py#L408) function with a Numba wrapper this significantly speeds up the calculation time since Numba precompiles the code and variables do not need to be reassigned each time they are called. 

> Numba is an open source JIT compiler that translates a subset of Python and NumPy code into fast machine code.

More info [on their website](https://numba.pydata.org)

**Comment by larsbuntemeyer** [comment]
i tested the new numpy version with [`utci` on climate model data](https://nbviewer.org/github/larsbuntemeyer/pythermalcomfort/blob/utci-notebook/examples/climate-model-input.ipynb
), it works great!

**Comment by FedericoTartarini** [comment]
You could add this example to the documentation since it looks great. We can consider either adding the link to the Jupiter notebook, or even better we could embed the code that generates the first figure in the documentation.

pythermalcomfort documentation is generated automatically by `Sphinx`. UTCI documentation is [here](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/fc143fe26637765518d97dcdd93d9fb821d56d89/src/pythermalcomfort/models.py#L1004)

**Comment by FedericoTartarini** [comment]
Hi, @larsbuntemeyer I just wanted to let you know that I was able to change most of the pythermalcomfort function so now you can pass arrays as an input, thank you for giving the idea. 

I was also able to further speed up the `utci` function by more than 200x since I used Numpy @vectorize decorator. 

Finally, I wanted to let you know that I changed the name of the variable `return_invald` to `check_compliance` which I believe it is more informative.

**Comment by larsbuntemeyer** [comment]
> Hi, @larsbuntemeyer I just wanted to let you know that I was able to change most of the pythermalcomfort function so now you can pass arrays as an input, thank you for giving the idea.
> 
> I was also able to further speed up the `utci` function by more than 200x since I used Numpy @vectorize decorator.
> 
> Finally, I wanted to let you know that I changed the name of the variable `return_invald` to `limit_inputs` which I believe is clearer.

That's great! I think this will make `pythermalcomfort` now more easily and efficiently available to the climate science community!

**Comment by FedericoTartarini** [comment]
Thank you. Please also let me know if there are some other indices that are not currently inside `pythermalcomfort` that you would like me to add.
