### ISSUE TITLE
Air speed limits from ASHRAE

### ISSUE THREAD

**Issue by adibantwal** [CenterForTheBuiltEnvironment/pythermalcomfort#32]
Hi,

In the ASHRAE Standard 55 2020, there is a flow chart which provides limits to local air speed inputs for different range of operative temperatures, depending on whether the occupant has local control or not of the air speed.

I just wanted to as if the pythermalcomfort accounts for this restriction?

Looking forward to your help, thanks in advance.

**Comment by FedericoTartarini** [comment]
No, currently `pythermalcomfort` does not yet take into account this restriction since only applies to a person that has no control of airspeed. If a person has control over airspeed then there is no limit. Consequently, we omitted this check. 

I could however add a new input to the PMV model which checks if the user has control over the airspeed and checks that V complies with this limit. Thank you for the suggestion.
