### ISSUE TITLE
Difference between SET* calculated by this package and SET* by CBE thermal comfort tool

### ISSUE THREAD

**Issue by meganefukawa** [CenterForTheBuiltEnvironment/pythermalcomfort#4]
Hello, @FedericoTartarini. This package is very helpful. Thank you for sharing it!

I have tried to calculate SET* by using "pythermalcomfort.models.set_tmp" as shown in follows:

```
import pythermalcomfort.models as ptc
ptc.set_tmp(tdb=25, tr=25, v=0.1, rh=50, met=1.8, clo=0.5)
>>> 29.0
```

In CBE Thermal Comfort Tool (`https://comfort.cbe.berkeley.edu/`), SET* was 25.2 °C in the same environment condition as shown in the following figure.
There is difference between SET* calculated by this package and SET* by CBE thermal comfort tool.
Do you know the cause of this result?

![01-1-01](https://user-images.githubusercontent.com/65655815/87559320-1c29a580-c6f5-11ea-8b91-d1b56ac6cbef.png)

Again, thank you  for your work!

Obs.: I'm currently running Python 3.7 through Anaconda, in Mac.

**Comment by FedericoTartarini** [comment]
Hi @meganefukawa thank you for contacting me and for using the pythermalcomfort package. 

The reason why you noticed that difference is because the CBE comfort tool automatically calculates the relative air velocity and the dynamic clothing insulation in the background, as required by the ASHRAE Standard. 

If you want to get the same results as the CBE thermal comfort tool, please first calculate the [relative air velocity using this equation](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#pythermalcomfort.psychrometrics.v_relative), and the [dynamic clothing insulation using this equation](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#pythermalcomfort.psychrometrics.clo_dynamic). 

Then enter the two calculated values as input in the SET model and the results obtained with the pythermalcomfort tool and the CBE thermal comfort tool should match. 

Please let me know if you still face any issues.
