### ISSUE TITLE
JOS3 documentation

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#58]
I have noticed that the documentation is not rendering well, the reason is that we should not have the Setters and Getters sections in the docstring. See an extract of the code that is causing an issue.

```
Setters
    -------
    tdb : float or array-like
        dry bulb air temperature [°C].
```

We should therefore remove the Setters and Getters sections and add the documentation directly inside the Setter or Getter function, as you have already done, for example in the code below:

```
    @property
    def tdb(self):
        """
        Getter
        Returns
        -------
        tdb : numpy.ndarray (17,)
            Air temperature [°C].
        """
        return self._ta
```

What do you think?

**Comment by AkihisaNomoto** [comment]
I don't know the right way to sync the documentation and I really rely on you about this part, so I will just let you modify the docstring. 

Maybe you can 1) remove Getter function there because honestly I don't expect the users use this function, and 2) add "Environmental Parameters" as Setter functions similer to "Other Parameters" in `wc` function, so that the documentation would render well? If this doesn't work, feel free to edit. 

If you teach me how documentation looks like on my local computer (not sure it is possible), I can repeatly fix the doctring and see the documentation until it looks nice.

**Comment by FedericoTartarini** [comment]
I have already fixed many issues, see the documentation online and the changes I pushed. Please let me know if you like my implementation. I need to find a way to separate setters and getters from functions. This [guide](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) should explain how to do it. While this is the [code style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) I am using. The only files you will need to edit are this one `docs/reference/pythermalcomfort.rst` and the file which contains your code. I have added this option `
   :undoc-members:` but we should have all the members documented.

1. Yes then let's remove the getter. Can we have only the setter and not the getter?
2. Do we really need the setters? I was reading [this article](https://realpython.com/python-property/) and they kind of show that the Python way is not to have setters or getters. I guess the advantage of having setters is that we can have some code validations, so consequently since you are using setters for data validation I am more than happy to keep them.
3. To run the documentation locally, the first command you need to run in the console is `tox -e docs` this will show you all the errors there are in the documentation. For example, some of the DOI you have added throw an error. Then navigate to the new folder that was created in the project repository called `dist/docs/index.html`. You can open this file with Chrome or any other browser and visualize the documentation locally.

For example the following code:
```python
# point.py

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        try:
            self._x = float(value)
            print("Validated!")
        except ValueError:
            raise ValueError('"x" must be a number') from None

    @property
    def y(self):
        return self._y

    @y.setter
    def y(self, value):
        try:
            self._y = float(value)
            print("Validated!")
        except ValueError:
            raise ValueError('"y" must be a number') from None
```

can be replaced with this one which is simpler to read.
```python
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
```

4. I am using the [Numpy docstring guide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). We should also look at this example below and in the website link, where they define the param1 args inside the __init__ docstring. This guide is very good since it explains how to write the docstring for all the setters, getters, and methods.

```
class ExampleClass(object):
    """The summary line for a class docstring should fit on one line.

    If the class has public attributes, they may be documented here
    in an ``Attributes`` section and follow the same formatting as a
    function's ``Args`` section. Alternatively, attributes may be documented
    inline with the attribute's declaration (see __init__ method below).

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes
    ----------
    attr1 : str
        Description of `attr1`.
    attr2 : :obj:`int`, optional
        Description of `attr2`.

    """

    def __init__(self, param1, param2, param3):
        """Example of docstring on the __init__ method.

        The __init__ method may be documented in either the class level
        docstring, or as a docstring on the __init__ method itself.

        Either form is acceptable, but the two should not be mixed. Choose one
        convention to document the __init__ method and be consistent with it.

        Note
        ----
        Do not include the `self` parameter in the ``Parameters`` section.

        Parameters
        ----------
        param1 : str
            Description of `param1`.
        param2 : :obj:`list` of :obj:`str`
            Description of `param2`. Multiple
            lines are supported.
        param3 : :obj:`int`, optional
            Description of `param3`.
```

**Comment by FedericoTartarini** [comment]
I have looked into creating documentation for the @property i.e. the getters. The guidelines say we should only document the getters, not the setters. 
> Only document the property’s “getter” method, not the “setter” (if present).

I am proposing to document them as follows:
```
   @property
    def tdb(self):
        """ Dry-bulb air temperature. The setter accepts int, float, dict, list,
        ndarray. The inputs are used to create a 17-element array. dict should
        be passed with BODY_NAMES as keys.

        Returns
        -------
        ndarray
            A NumPy array of shape (17,).
        """
        return self._ta
```

which renders like this:
![image](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/assets/40018640/ca6996bf-b73c-4ca8-84af-9bd1a1146609)

What do you think?

I have also made a lot of other changes and improvements.

**Comment by AkihisaNomoto** [comment]
I checked the documentation online. It looks really good. Thank you for implementing this.

> * Yes then let's remove the getter. Can we have only the setter and not the getter?
Oh, I meant that we could remove the getters in the docstring, not the code. If we should only document the getters (not the setters)
> * Do we really need the setters? I was reading [this article](https://realpython.com/python-property/) and they kind of show that the Python way is not to have setters or getters. I guess the advantage of having setters is that we can have some code validations, so consequently since you are using setters for data validation I am more than happy to keep them.
That is something my former colleagues implemented, but I think the setter is useful when we want to do a transient simulation.
> * To run the documentation locally, the first command you need to run in the console is `tox -e docs` this will show you all the errors there are in the documentation. For example, some of the DOI you have added throw an error. Then navigate to the new folder that was created in the project repository called `dist/docs/index.html`. You can open this file with Chrome or any other browser and visualize the documentation locally.
Thanks, but I can't find `dist/docs/index.html`..., so I will just let you edit, but please let me know if there is anything I can help for this documenting work.
> 4\. I am using the [Numpy docstring guide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). We should also look at this example below and in the website link, where they define the param1 args inside the **init** docstring. This guide is very good since it explains how to write the docstring for all the setters, getters, and methods.
Thank you, this is really helpful. According to this, should the Attributes section is under the JOS3 class docstring, not under __init__ function? The current Attributes (Variables) online are all getters. I think in this section we should only show setters (input condition), which you mentioned is mayber difficult to implement. However, the following parameters are both setter and getter, so we should be able to show them by removing the rest of the getters such as bsa, Rt, Ret and so on.

> tdb : float or array-like
>     dry bulb air temperature [°C].
> tr : float or list-like
>     Mean radiant temperature [°C].
> to : float or list-like
>     Operative temperature [°C].
> v : float or list-like
>     Air speed [m/s].
> rh : float or list-like
>     Relative humidity [%].
> clo : float or list-like
>     Clothing insulation [clo].
>     Note: If you want to input clothing insulation to each body part,
>     it can be input using the dictionaly in utilities.py.
>     :py:meth:`pythermalcomfort.utilities.local_clo_typical_ensembles`.
> par : float
>     Physical activity ratio [-].
>     This equals the ratio of metaboric rate to basal metablic rate.
>     The par of sitting quietly is 1.2.
> posture : str
>     Choose a posture from standing, sitting or lying.
> bodytemp : numpy.ndarray (85,)
>     All segment temperatures of JOS-3

Again, please let me know if there is anyting that I can help. Thanks!

**Comment by AkihisaNomoto** [comment]
I checked the documentation online. It looks really good. Thank you for implementing this.

Yes then let's remove the getter. Can we have only the setter and not the getter?
Oh, I meant that we could remove the getters in the docstring, not the code. If we should only document the getters (not the setters)
Do we really need the setters? I was reading [this article](https://realpython.com/python-property/) and they kind of show that the Python way is not to have setters or getters. I guess the advantage of having setters is that we can have some code validations, so consequently since you are using setters for data validation I am more than happy to keep them.
That is something my former colleagues implemented, but I think the setter is useful when we want to do a transient simulation.
To run the documentation locally, the first command you need to run in the console is tox -e docs this will show you all the errors there are in the documentation. For example, some of the DOI you have added throw an error. Then navigate to the new folder that was created in the project repository called dist/docs/index.html. You can open this file with Chrome or any other browser and visualize the documentation locally.
Thanks, but I can't find dist/docs/index.html..., so I will just let you edit, but please let me know if there is anything I can help for this documenting work.
4. I am using the [Numpy docstring guide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). We should also look at this example below and in the website link, where they define the param1 args inside the init docstring. This guide is very good since it explains how to write the docstring for all the setters, getters, and methods.
Thank you, this is really helpful. According to this, should the Attributes section is under the JOS3 class docstring, not under init function? The current Attributes (Variables) online are all getters. I think in this section we should only show setters (input condition) because it is the most important for the users, which you mentioned is maybe difficult to implement. However, the following parameters are both setter and getter, so we should be able to show them by removing the rest of the getters such as bsa, Rt, Ret and so on.
tdb : float or array-like
dry bulb air temperature [°C].
tr : float or list-like
Mean radiant temperature [°C].
to : float or list-like
Operative temperature [°C].
v : float or list-like
Air speed [m/s].
rh : float or list-like
Relative humidity [%].
clo : float or list-like
Clothing insulation [clo].
Note: If you want to input clothing insulation to each body part,
it can be input using the dictionaly in utilities.py.
:py:meth:pythermalcomfort.utilities.local_clo_typical_ensembles.
par : float
Physical activity ratio [-].
This equals the ratio of metaboric rate to basal metablic rate.
The par of sitting quietly is 1.2.
posture : str
Choose a posture from standing, sitting or lying.
bodytemp : numpy.ndarray (85,)
All segment temperatures of JOS-3

Again, please let me know if there is anyting that I can help. Thanks!

**Comment by FedericoTartarini** [comment]
Okay so let's keep the getters and setters as they are since they are now rendering well in the documentation.

Did you run `tox -e docs`? You need to run it each time you want to update the documentation and see if there are any errors. To run tox you need to have python 3.10 installed

> According to this, should the Attributes section is under the JOS3 class docstring, not under init function? The current Attributes (Variables) online are all getters. I think in this section we should only show setters (input condition), because that is actually important for the users, which you mentioned is maybe difficult to implement.

I have moved the setters inside the parameters since personally, I do not see much of the difference between the two. While I removed the getters since these are already included in the output and I am not sure people will want to access them individually. What do you think? I have pushed the changes online to the documentation website.

**Comment by AkihisaNomoto** [comment]
> Did you run `tox -e docs`? You need to run it each time you want to update the documentation and see if there are any errors. To run tox you need to have python 3.10 installed

I see, that's the reason, I am using python 3.9. Are you using python 3.10 or python 3.11? I will use the same version for the further development to avoid the issue caused by the verion difference.

The current documentation shows both body and environmental parameters in the same 'Parameters' section. Could you please separete body parameters and environmental parameters because the arguments for JOS3 class itself are body parameters and we can set the environmental parameters as Setter method. How about showing body parametes in the ”Parameters” section and environmental parameters in another section (name it ”Attributes” or ”Environmental Parameters”, for example)?
![image](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/assets/67300161/f8581a07-6ba0-4b49-b575-191f7664a5aa)

**Comment by FedericoTartarini** [comment]
Regarding tox please refer to the `tox.ini` file line 27 that tells you which Python version is required to run the above mentioned command. This line could also be changed in the future. At the moment I am using Python 3.10 since I belive that 3.11 had some issues with Numba.

> How about showing body parametes in the ”Parameters” section and environmental parameters in another section (name it ”Attributes” or ”Environmental Parameters”, for example)?

I have implemented this. Unfortunately, I cannot use a custom name for the section like Environmental Parameters otherwise it breaks the documentation. Hence, i place them under the Attributes heading.

**Comment by AkihisaNomoto** [comment]
I noticed that there is some mistakes in the docstring of JOS model (my bad), so I opened new pull request.

**Comment by FedericoTartarini** [comment]
Me too I am very excited that now we have the JOS3 model in pythermalcomfort. Thank you so much for your help in making this happen. I believe we can close this issue since it is mainly resolved. One thing that is missing perhaps is to review the docstring of all the nested functions to make sure they are informative and nicely formatted.
